// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurveySystem.Infrastructure.Persistance;

#nullable disable

namespace SurveySystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225103353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SurveySystem.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CompositeTaxRate")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("Jurisdictions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SurveySystem.Domain.Entities.TaxZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry");

                    b.Property<decimal>("CityRate")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<decimal>("CountyRate")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SpecialRates")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<decimal>("StateRate")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.HasKey("Id");

                    b.ToTable("TaxZones");
                });

            modelBuilder.Entity("SurveySystem.Domain.Entities.Order", b =>
                {
                    b.OwnsOne("SurveySystem.Domain.ValueObjects.TaxBreakdown", "Breakdown", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CityRate")
                                .HasPrecision(10, 5)
                                .HasColumnType("numeric(10,5)")
                                .HasColumnName("CityRate");

                            b1.Property<decimal>("CountyRate")
                                .HasPrecision(10, 5)
                                .HasColumnType("numeric(10,5)")
                                .HasColumnName("CountyRate");

                            b1.Property<decimal>("SpecialRates")
                                .HasPrecision(10, 5)
                                .HasColumnType("numeric(10,5)")
                                .HasColumnName("SpecialRates");

                            b1.Property<decimal>("StateRate")
                                .HasPrecision(10, 5)
                                .HasColumnType("numeric(10,5)")
                                .HasColumnName("StateRate");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Breakdown");
                });
#pragma warning restore 612, 618
        }
    }
}
